site_name: Panentheon
repo_url: https://github.com/openartist/panentheon
edit_uri: edit/main/docs/
theme:
  name: material
  logo: assets/images/logo.svg
  favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  palette:
    - scheme: default
      primary: white
      accent: black
  extra:
    generator: false
  copyright: Copyright &copy; Panentheon
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to dark mode
    # - scheme: slate
    #   primary: black
    #   accent: indigo
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to light mode

nav:
  - Home: index.md
  - About: about.md
  - Contributor Guide: contributor_guide.md

extra_css:
  - assets/stylesheets/extra.css