site_name: Panentheon
repo_url: https://github.com/openartist/panentheon
edit_uri: edit/main/docs/
theme:
  name: material
  custom_dir: material/overrides
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico
  features:
    - navigation.tabs
    - navigation.sections
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  palette:
    - scheme: default
      primary: white
      accent: black
  copyright: Copyright &copy; "Apeiron et Kosmos"
  extra:
    generator: false

extra_css:
  - assets/stylesheets/extra.css

extra:
  generator: false

nav:
  - About:
    - Introduction: index.md
    - A Universal Rite: universal-rite.md
    - A History of Consciousness: historia.md
    - Catechism: catechism.md
    - Diakrisis - Distinctions: diakrisis-distinctions.md
    - Transmission of Light: lineage.md
  - Typikon:
    - Introduction: typikon.md 
    - Interpretatio - Glossary: glossary/interpretatio-universalis.md
    - Iconotheca - Iconography: iconotheca-universalis.md
    - Thesmoi - Codes of Conduct: thesmoi.md
    - Amphia - Vestments: typikon.md
    - Ascesis - Practices: ascesis.md
    - Kosmographia - Maps: kosmographia.md
    - Daimonologia - Divine Beings: daimonologia.md
    - Anthologia - Quotes of the Sages: anthologia.md
    - Soma Kosmikon - Corpus: soma-kosmikon.md
  - Contributor Guide: contributor_guide.md
